workflows:
  build-android-debug:
    name: Build Android Debug APK
    environment:
      flutter: stable
    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get

      - name: .env file yaratish
        script: |
          echo "SPOTIFY_CLIENT_ID=2f8e06f1892f43bcbf2faabc0298cef5" > .env
          echo "SPOTIFY_REDIRECT_URI=spotube://callback" >> .env

      - name: Android debug build
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
