workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        DART_DEFINES: ""
    scripts:
      - name: Dependencies o‘rnatish
        script: |
          flutter pub get
      - name: .env yaratish (agar yo‘q bo‘lsa)
        script: |
          if [ ! -f .env ]; then
            echo "SPOTIFY_CLIENT_ID=YOUR_CLIENT_ID" >> .env
            echo "SPOTIFY_REDIRECT_URI=spotube://callback" >> .env
          fi
      - name: Android Debug APK build qilish
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
